### PR TITLE
ManufacturerProprietary for Fibaro FGRM-222

### PR DESCRIPTION
**Pull request by ChristianKuehnel**
This patch was already merged to upstream master. I back-ported it to the hass branch, so that it can be used from HomeAssistant.

This adds support for the proprietary venetian blind mode for the "Fibaro FGRM-222 Roller Shutter 2" cover controller. With this change the tilt angle of the venetian blinds can be controlled via ZWave.

In parallel I'm working on adding the support for this to Home Assistant, there we also need an extension...

Alternative: If the upstream realease 1.6 of open-zwave is used, this patch is not required any more, as 1.6 already contains this patch. The change to Home Assistant is required any way to support this.

### CODE REVIEW

**Comment by ChristianKuehnel** [comment]
These changes are working, but I'm stuck implementing the upper layers in HomeAssistant. Any help is appreciated.

https://community.home-assistant.io/t/zwave-cannot-read-values-from-command-class-manufacturer-proprietary-145dec-91hex/119553

**Comment by andre-richter** [comment]
@pvizeli, the [referenced PR](https://github.com/home-assistant/home-assistant/pull/24405) that depends on this one is now working tested and just waiting for final review.

What are your plans regarding this dependency PR?

Thanks,
Andre

**Comment by andre-richter** [comment]
@ChristianKuehnel, your `OZW_log.txt` accidentally slipped into this PR.

**Comment by ChristianKuehnel** [comment]
@andre-richter thx for spotting :sunglasses: that, just fixed it.

**Comment by ChristianKuehnel** [comment]
@pvizeli how do you want to proceed here?

**Pull request merged**
